<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FishingAssistant</AssemblyName>
    <RootNamespace>FishingAssistant</RootNamespace>
    <Description>A configurable fishing assistant for Stardew Valley.</Description>
    <VersionPrefix>3.0.0</VersionPrefix>
    <VersionSuffix>alpha.1</VersionSuffix>

    <EnableModDeploy>false</EnableModDeploy>
    <EnableModZip>false</EnableModZip>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" />
  </ItemGroup>
</Project>
