<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FishingAssistant</AssemblyName>
    <RootNamespace>FishingAssistant</RootNamespace>
    <Description>A configurable fishing assistant for Stardew Valley.</Description>
    <VersionPrefix>3.4.1</VersionPrefix>

    <EnableModDeploy>false</EnableModDeploy>
    <EnableModZip>false</EnableModZip>
    <EnableHarmony>true</EnableHarmony>

    <FishingAssistantTestBuild Condition="'$(FishingAssistantTestBuild)' == ''">false</FishingAssistantTestBuild>
    <DefineConstants Condition="'$(FishingAssistantTestBuild)' == 'true'">$(DefineConstants);FISHING_ASSISTANT_TEST_BUILD</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" />
  </ItemGroup>
</Project>
